services:
  db:
    image: postgres:15
    container_name: trd-01-postgres
    environment:
      POSTGRES_DB: {db-name}
      POSTGRES_USER: {db-user}
      POSTGRES_PASSWORD: {db-password}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: trd-01-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata:
